service: itsm-stream-demo36

provider:
  name: aws
  runtime: nodejs10.x

  plugins:
     - serverless-iam-roles-per-function

  environment:
    websocketIDTable:
      Ref: websocketIDTableNew1111
    demoTable:
      Ref: demoTableNew1111

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [websocketIDTableNew1111, Arn]
    

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams

      Resource:
        - Fn::GetAtt: [demoTableNew1111, Arn]

functions:
  connectionHandler:
    handler: handler/handler.connectionHandler
    events:
      - websocket:
          route: $connect
          cors: true
      - websocket:
          route: $disconnect
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

  defaultHandler:
    handler: handler/handler.defaultHandler
    events:
      - websocket:
          route: $default
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

  sendMessageHandler:
    handler: handler/handler.sendMessageHandler
    events:
      - websocket:
          route: sendMessage
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

  getStream:
    handler: handler/stream.getStream
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          cors: true
          arn:
            Fn::GetAtt:
              - demoTableNew1111
              - StreamArn
    iamRoleStatementsInherit: true
    iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
        
resources:
  Resources:
    websocketIDTableNew1111:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "connectionId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "connectionId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: websocketIDTableNew1111

    demoTableNew1111:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: demoTableNew1111
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH